name: Claude Denied Tools Action
description: Report a list of tools that were denied due to insufficient permissions when used by Claude Code Action.

branding:
  icon: shield-off
  color: red

inputs:
  github-token:
    description: GitHub token for API access
    required: false
    default: ${{ github.token }}
  claude-code-execution-file:
    description: The outputs.execution_file from anthropics/claude-code-action
    required: true
  sticky-comment:
    description: If true, updates existing comment instead of creating new ones for each run
    required: false
    default: "false"
  skip-comment:
    description: If true, skip creating/updating PR/Issue comments
    required: false
    default: "false"

outputs:
  report:
    description: Markdown-formatted report of denied tool executions
  denied-tools:
    description: List of denied tools (JSON)
  found:
    description: Whether any denied tools were found (boolean)

runs:
  using: node20
  main: dist/index.js
